## Copyright Opsolving. All Rights Reserved.
## SPDX-License-Identifier: APACHE-2.0

apiVersion: v2
name: extra

description: A Helm chart for Kubernetes

type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x