apiVersion: v2
name: extra-manifest

description: A Helm chart for Kubernetes

type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x