# Copyright Opsolving. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

## @section Global parameters

## @param nameOverride String to partially override `common.names.fullname`
nameOverride: ""

## @param fullnameOverride String to fully override `common.names.fullname`
fullnameOverride: ""

## @param namespaceOverride String to fully override `common.names.namespace`
namespaceOverride: ""

## @section Extra-manifest parameters

## @param releaseNamePrefix Whether to prefix object names with chart fullname
## If true (default), object names are rendered as `<fullname>-<name>`.
## If false, object names use only the provided key from `extraManifests`.
releaseNamePrefix: true

## @param commonLabels Labels to add to all rendered objects
commonLabels: { }

## @param commonAnnotations Annotations to add to all rendered objects
commonAnnotations: { }

## @param extraManifests Object map of user-defined manifests grouped by a first-level key
## Example:
## extraManifests:
##   secrets:
##     token:
##       apiVersion: v1
##       kind: Secret
extraManifests: {}